import "./globals.css";
import { Inter } from "next/font/google";
import AppBar from "./components/AppBar";
import Footer from "./components/Footer";
import Breadcrumbs from "./components/Breadcrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <AppBar />
          <Breadcrumbs/>
          {children}
          <Footer/>
        </body>
      </html>
    </>
  );
}
