"use client";

import Box from "@mui/material/Box";
import { ThemeProvider } from "@mui/material/styles";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Breadcrumbs from "@/components/Breadcrumbs";
import Footer from "@/components/Footer";
import "./globals.css";
import { theme } from "../[lang]/theme";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <Breadcrumbs />
          <Box
            alignItems="center"
            border="1px solid red"
            display="flex"
            flexDirection="column"
            minHeight="calc(100vh - 181px)"
            padding="60px 20px 20px"
          >
            {children}
          </Box>
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  );
}
